spring:
  application:
    name: backend
  data:
    mongodb:
      url: mongodb+srv://MOIDA_DB:DRXznUwGozg1c0ZO@cluster0.ujgb2fn.mongodb.net/

  jwt:
    secret: ${JWT_SECRET}
    access-expiration: ${JWT_ACCESS_EXPIRATION}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}